export const cinemaData = [
  {
    id: 1,
    salon: 1,
    filmAdi: "Doktor Strange Çoklu Evren Çılgınlığında",
    image:"https://tr.web.img4.acsta.net/c_310_420/pictures/22/05/05/14/02/4321698.jpg",
    fiyat: 25,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 1, secildi: 0 },
      { id: 2, alinabilir: 1, secildi: 0 },
      { id: 3, alinabilir: 0, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 0, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 0, secildi: 0 },
      { id: 9, alinabilir: 1, secildi: 0 },
      { id: 10, alinabilir: 1, secildi: 0 },
      { id: 11, alinabilir: 1, secildi: 0 },
      { id: 12, alinabilir: 1, secildi: 0 },
      { id: 13, alinabilir: 1, secildi: 0 },
      { id: 14, alinabilir: 1, secildi: 0 },
      { id: 15, alinabilir: 0, secildi: 0 },
      { id: 16, alinabilir: 0, secildi: 0 },
      { id: 17, alinabilir: 1, secildi: 0 },
      { id: 18, alinabilir: 0, secildi: 0 },
      { id: 19, alinabilir: 0, secildi: 0 },
      { id: 20, alinabilir: 1, secildi: 0 },
      { id: 21, alinabilir: 1, secildi: 0 },
      { id: 22, alinabilir: 0, secildi: 0 },
      { id: 23, alinabilir: 1, secildi: 0 },
      { id: 24, alinabilir: 1, secildi: 0 },
      { id: 25, alinabilir: 0, secildi: 0 },
      { id: 26, alinabilir: 0, secildi: 0 },
      { id: 27, alinabilir: 1, secildi: 0 },
      { id: 28, alinabilir: 1, secildi: 0 },
      { id: 29, alinabilir: 1, secildi: 0 },
      { id: 30, alinabilir: 1, secildi: 0 },
      { id: 31, alinabilir: 1, secildi: 0 },
      { id: 32, alinabilir: 1, secildi: 0 },
      { id: 33, alinabilir: 0, secildi: 0 },
      { id: 34, alinabilir: 0, secildi: 0 },
      { id: 35, alinabilir: 0, secildi: 0 },
      { id: 36, alinabilir: 0, secildi: 0 },
      { id: 37, alinabilir: 1, secildi: 0 },
      { id: 38, alinabilir: 1, secildi: 0 },
      { id: 39, alinabilir: 1, secildi: 0 },
      { id: 40, alinabilir: 1, secildi: 0 },
      { id: 41, alinabilir: 1, secildi: 0 },
      { id: 42, alinabilir: 1, secildi: 0 },
      { id: 43, alinabilir: 1, secildi: 0 },
      { id: 44, alinabilir: 1, secildi: 0 }
    ],
  },
  {
    id: 2,
    salon: 2,
    filmAdi: "Jurassic World: Hakimiyet",
    image:"https://tr.web.img4.acsta.net/pictures/22/04/29/10/46/0161380.jpg",
    fiyat: 25,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 1, secildi: 0 },
      { id: 2, alinabilir: 1, secildi: 0 },
      { id: 3, alinabilir: 0, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 0, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 0, secildi: 0 },
      { id: 9, alinabilir: 1, secildi: 0 },
      { id: 10, alinabilir: 1, secildi: 0 },
      { id: 11, alinabilir: 1, secildi: 0 },
      { id: 12, alinabilir: 1, secildi: 0 },
      { id: 13, alinabilir: 1, secildi: 0 },
      { id: 14, alinabilir: 1, secildi: 0 },
      { id: 15, alinabilir: 0, secildi: 0 },
      { id: 16, alinabilir: 0, secildi: 0 },
      { id: 17, alinabilir: 1, secildi: 0 },
      { id: 18, alinabilir: 0, secildi: 0 },
      { id: 19, alinabilir: 0, secildi: 0 },
      { id: 20, alinabilir: 1, secildi: 0 },
      { id: 21, alinabilir: 1, secildi: 0 },
      { id: 22, alinabilir: 0, secildi: 0 },
      { id: 23, alinabilir: 1, secildi: 0 },
      { id: 24, alinabilir: 1, secildi: 0 },
      { id: 25, alinabilir: 0, secildi: 0 },
      { id: 26, alinabilir: 0, secildi: 0 },
      { id: 27, alinabilir: 1, secildi: 0 },
      { id: 28, alinabilir: 1, secildi: 0 },
      { id: 29, alinabilir: 1, secildi: 0 },
      { id: 30, alinabilir: 1, secildi: 0 },
      { id: 31, alinabilir: 1, secildi: 0 },
      { id: 32, alinabilir: 1, secildi: 0 },
      { id: 33, alinabilir: 0, secildi: 0 },
      { id: 34, alinabilir: 0, secildi: 0 },
      { id: 35, alinabilir: 0, secildi: 0 },
      { id: 36, alinabilir: 0, secildi: 0 },
      { id: 37, alinabilir: 1, secildi: 0 },
      { id: 38, alinabilir: 1, secildi: 0 },
      { id: 39, alinabilir: 1, secildi: 0 },
      { id: 40, alinabilir: 1, secildi: 0 },
      { id: 41, alinabilir: 1, secildi: 0 },
      { id: 42, alinabilir: 1, secildi: 0 },
      { id: 43, alinabilir: 1, secildi: 0 },
      { id: 44, alinabilir: 1, secildi: 0 }
    ],
  },
  {
    id: 3,
    salon: 3,
    filmAdi: "Mutlu Oyuncak Dükkanı",
    image:"https://media.cinemaximum.com.tr/255//Files/POSTER/mutlu_oyuncak_dukkani.png",
    fiyat: 25,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 1, secildi: 0 },
      { id: 2, alinabilir: 1, secildi: 0 },
      { id: 3, alinabilir: 0, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 0, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 0, secildi: 0 },
      { id: 9, alinabilir: 1, secildi: 0 },
      { id: 10, alinabilir: 1, secildi: 0 },
      { id: 11, alinabilir: 1, secildi: 0 },
      { id: 12, alinabilir: 1, secildi: 0 },
      { id: 13, alinabilir: 1, secildi: 0 },
      { id: 14, alinabilir: 1, secildi: 0 },
      { id: 15, alinabilir: 0, secildi: 0 },
      { id: 16, alinabilir: 0, secildi: 0 },
      { id: 17, alinabilir: 1, secildi: 0 },
      { id: 18, alinabilir: 0, secildi: 0 },
      { id: 19, alinabilir: 0, secildi: 0 },
      { id: 20, alinabilir: 1, secildi: 0 },
      { id: 21, alinabilir: 1, secildi: 0 },
      { id: 22, alinabilir: 0, secildi: 0 },
      { id: 23, alinabilir: 1, secildi: 0 },
      { id: 24, alinabilir: 1, secildi: 0 },
      { id: 25, alinabilir: 0, secildi: 0 },
      { id: 26, alinabilir: 0, secildi: 0 },
      { id: 27, alinabilir: 1, secildi: 0 },
      { id: 28, alinabilir: 1, secildi: 0 },
      { id: 29, alinabilir: 1, secildi: 0 },
      { id: 30, alinabilir: 1, secildi: 0 },
      { id: 31, alinabilir: 1, secildi: 0 },
      { id: 32, alinabilir: 1, secildi: 0 },
      { id: 33, alinabilir: 0, secildi: 0 },
      { id: 34, alinabilir: 0, secildi: 0 },
      { id: 35, alinabilir: 0, secildi: 0 },
      { id: 36, alinabilir: 0, secildi: 0 },
      { id: 37, alinabilir: 1, secildi: 0 },
      { id: 38, alinabilir: 1, secildi: 0 },
      { id: 39, alinabilir: 1, secildi: 0 },
      { id: 40, alinabilir: 1, secildi: 0 },
      { id: 41, alinabilir: 1, secildi: 0 },
      { id: 42, alinabilir: 1, secildi: 0 },
      { id: 43, alinabilir: 1, secildi: 0 },
      { id: 44, alinabilir: 1, secildi: 0 }
    ],
  },
  {
    id: 4,
    salon: 4,
    filmAdi: "Asi Prenses",
    image:"https://media.cinemaximum.com.tr/255//Files/POSTER/asi_prenses.jpg",
    fiyat: 25,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 1, secildi: 0 },
      { id: 2, alinabilir: 1, secildi: 0 },
      { id: 3, alinabilir: 0, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 0, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 0, secildi: 0 },
      { id: 9, alinabilir: 1, secildi: 0 },
      { id: 10, alinabilir: 1, secildi: 0 },
      { id: 11, alinabilir: 1, secildi: 0 },
      { id: 12, alinabilir: 1, secildi: 0 },
      { id: 13, alinabilir: 1, secildi: 0 },
      { id: 14, alinabilir: 1, secildi: 0 },
      { id: 15, alinabilir: 0, secildi: 0 },
      { id: 16, alinabilir: 0, secildi: 0 },
      { id: 17, alinabilir: 1, secildi: 0 },
      { id: 18, alinabilir: 0, secildi: 0 },
      { id: 19, alinabilir: 0, secildi: 0 },
      { id: 20, alinabilir: 1, secildi: 0 },
      { id: 21, alinabilir: 1, secildi: 0 },
      { id: 22, alinabilir: 0, secildi: 0 },
      { id: 23, alinabilir: 1, secildi: 0 },
      { id: 24, alinabilir: 1, secildi: 0 },
      { id: 25, alinabilir: 0, secildi: 0 },
      { id: 26, alinabilir: 0, secildi: 0 },
      { id: 27, alinabilir: 1, secildi: 0 },
      { id: 28, alinabilir: 1, secildi: 0 },
      { id: 29, alinabilir: 1, secildi: 0 },
      { id: 30, alinabilir: 1, secildi: 0 },
      { id: 31, alinabilir: 1, secildi: 0 },
      { id: 32, alinabilir: 1, secildi: 0 },
      { id: 33, alinabilir: 0, secildi: 0 },
      { id: 34, alinabilir: 0, secildi: 0 },
      { id: 35, alinabilir: 0, secildi: 0 },
      { id: 36, alinabilir: 0, secildi: 0 },
      { id: 37, alinabilir: 1, secildi: 0 },
      { id: 38, alinabilir: 1, secildi: 0 },
      { id: 39, alinabilir: 1, secildi: 0 },
      { id: 40, alinabilir: 1, secildi: 0 },
      { id: 41, alinabilir: 1, secildi: 0 },
      { id: 42, alinabilir: 1, secildi: 0 },
      { id: 43, alinabilir: 1, secildi: 0 },
      { id: 44, alinabilir: 1, secildi: 0 }
    ],
  },
  {
    id: 5,
    salon: 3,
    filmAdi: "Köşk-ü Ammar",
    image:"https://tr.web.img3.acsta.net/pictures/22/05/29/21/19/2270272.png",
    fiyat: 25,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 1, secildi: 0 },
      { id: 2, alinabilir: 1, secildi: 0 },
      { id: 3, alinabilir: 0, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 0, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 0, secildi: 0 },
      { id: 9, alinabilir: 1, secildi: 0 },
      { id: 10, alinabilir: 1, secildi: 0 },
      { id: 11, alinabilir: 1, secildi: 0 },
      { id: 12, alinabilir: 1, secildi: 0 },
      { id: 13, alinabilir: 1, secildi: 0 },
      { id: 14, alinabilir: 1, secildi: 0 },
      { id: 15, alinabilir: 0, secildi: 0 },
      { id: 16, alinabilir: 0, secildi: 0 },
      { id: 17, alinabilir: 1, secildi: 0 },
      { id: 18, alinabilir: 0, secildi: 0 },
      { id: 19, alinabilir: 0, secildi: 0 },
      { id: 20, alinabilir: 1, secildi: 0 },
      { id: 21, alinabilir: 1, secildi: 0 },
      { id: 22, alinabilir: 0, secildi: 0 },
      { id: 23, alinabilir: 1, secildi: 0 },
      { id: 24, alinabilir: 1, secildi: 0 },
      { id: 25, alinabilir: 0, secildi: 0 },
      { id: 26, alinabilir: 0, secildi: 0 },
      { id: 27, alinabilir: 1, secildi: 0 },
      { id: 28, alinabilir: 1, secildi: 0 },
      { id: 29, alinabilir: 1, secildi: 0 },
      { id: 30, alinabilir: 1, secildi: 0 },
      { id: 31, alinabilir: 1, secildi: 0 },
      { id: 32, alinabilir: 1, secildi: 0 },
      { id: 33, alinabilir: 0, secildi: 0 },
      { id: 34, alinabilir: 0, secildi: 0 },
      { id: 35, alinabilir: 0, secildi: 0 },
      { id: 36, alinabilir: 0, secildi: 0 },
      { id: 37, alinabilir: 1, secildi: 0 },
      { id: 38, alinabilir: 1, secildi: 0 },
      { id: 39, alinabilir: 1, secildi: 0 },
      { id: 40, alinabilir: 1, secildi: 0 },
      { id: 41, alinabilir: 1, secildi: 0 },
      { id: 42, alinabilir: 1, secildi: 0 },
      { id: 43, alinabilir: 1, secildi: 0 },
      { id: 44, alinabilir: 1, secildi: 0 }
    ],
  },
  {
    id: 6,
    salon: 4,
    filmAdi: "Justice League",
    image:"https://images-na.ssl-images-amazon.com/images/I/81KX513BQxL.jpg",
    fiyat: 25,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 1, secildi: 0 },
      { id: 2, alinabilir: 1, secildi: 0 },
      { id: 3, alinabilir: 0, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 0, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 0, secildi: 0 },
      { id: 9, alinabilir: 1, secildi: 0 },
      { id: 10, alinabilir: 1, secildi: 0 },
      { id: 11, alinabilir: 1, secildi: 0 },
      { id: 12, alinabilir: 1, secildi: 0 },
      { id: 13, alinabilir: 1, secildi: 0 },
      { id: 14, alinabilir: 1, secildi: 0 },
      { id: 15, alinabilir: 0, secildi: 0 },
      { id: 16, alinabilir: 0, secildi: 0 },
      { id: 17, alinabilir: 1, secildi: 0 },
      { id: 18, alinabilir: 0, secildi: 0 },
      { id: 19, alinabilir: 0, secildi: 0 },
      { id: 20, alinabilir: 1, secildi: 0 },
      { id: 21, alinabilir: 1, secildi: 0 },
      { id: 22, alinabilir: 0, secildi: 0 },
      { id: 23, alinabilir: 1, secildi: 0 },
      { id: 24, alinabilir: 1, secildi: 0 },
      { id: 25, alinabilir: 0, secildi: 0 },
      { id: 26, alinabilir: 0, secildi: 0 },
      { id: 27, alinabilir: 1, secildi: 0 },
      { id: 28, alinabilir: 1, secildi: 0 },
      { id: 29, alinabilir: 1, secildi: 0 },
      { id: 30, alinabilir: 1, secildi: 0 },
      { id: 31, alinabilir: 1, secildi: 0 },
      { id: 32, alinabilir: 1, secildi: 0 },
      { id: 33, alinabilir: 0, secildi: 0 },
      { id: 34, alinabilir: 0, secildi: 0 },
      { id: 35, alinabilir: 0, secildi: 0 },
      { id: 36, alinabilir: 0, secildi: 0 },
      { id: 37, alinabilir: 1, secildi: 0 },
      { id: 38, alinabilir: 1, secildi: 0 },
      { id: 39, alinabilir: 1, secildi: 0 },
      { id: 40, alinabilir: 1, secildi: 0 },
      { id: 41, alinabilir: 1, secildi: 0 },
      { id: 42, alinabilir: 1, secildi: 0 },
      { id: 43, alinabilir: 1, secildi: 0 },
      { id: 44, alinabilir: 1, secildi: 0 }

    ],
  },
  {
    id: 7,
    salon: 1,
    filmAdi: "Top Gun: Maverick",
    image:"https://media.cinemaximum.com.tr/255//Files/POSTER/top_gun_maverick.jpg",
    fiyat: 25,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 1, secildi: 0 },
      { id: 2, alinabilir: 1, secildi: 0 },
      { id: 3, alinabilir: 0, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 0, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 0, secildi: 0 },
      { id: 9, alinabilir: 1, secildi: 0 },
      { id: 10, alinabilir: 1, secildi: 0 },
      { id: 11, alinabilir: 1, secildi: 0 },
      { id: 12, alinabilir: 1, secildi: 0 },
      { id: 13, alinabilir: 1, secildi: 0 },
      { id: 14, alinabilir: 1, secildi: 0 },
      { id: 15, alinabilir: 0, secildi: 0 },
      { id: 16, alinabilir: 0, secildi: 0 },
      { id: 17, alinabilir: 1, secildi: 0 },
      { id: 18, alinabilir: 0, secildi: 0 },
      { id: 19, alinabilir: 0, secildi: 0 },
      { id: 20, alinabilir: 1, secildi: 0 },
      { id: 21, alinabilir: 1, secildi: 0 },
      { id: 22, alinabilir: 0, secildi: 0 },
      { id: 23, alinabilir: 1, secildi: 0 },
      { id: 24, alinabilir: 1, secildi: 0 },
      { id: 25, alinabilir: 0, secildi: 0 },
      { id: 26, alinabilir: 0, secildi: 0 },
      { id: 27, alinabilir: 1, secildi: 0 },
      { id: 28, alinabilir: 1, secildi: 0 },
      { id: 29, alinabilir: 1, secildi: 0 },
      { id: 30, alinabilir: 1, secildi: 0 },
      { id: 31, alinabilir: 1, secildi: 0 },
      { id: 32, alinabilir: 1, secildi: 0 },
      { id: 33, alinabilir: 0, secildi: 0 },
      { id: 34, alinabilir: 0, secildi: 0 },
      { id: 35, alinabilir: 0, secildi: 0 },
      { id: 36, alinabilir: 0, secildi: 0 },
      { id: 37, alinabilir: 1, secildi: 0 },
      { id: 38, alinabilir: 1, secildi: 0 },
      { id: 39, alinabilir: 1, secildi: 0 },
      { id: 40, alinabilir: 1, secildi: 0 },
      { id: 41, alinabilir: 1, secildi: 0 },
      { id: 42, alinabilir: 1, secildi: 0 },
      { id: 43, alinabilir: 1, secildi: 0 },
      { id: 44, alinabilir: 1, secildi: 0 }
    ],
  },
];
